### PR TITLE
Added support for urlparse functions

### PR DESCRIPTION
**Pull request by sagararora19992**

### CODE REVIEW

**Review by VMRuiz — CHANGES_REQUESTED** [review]
Hello Sagar, 

Maybe you can add an additional method that just return all the urlparse info as a dictionary? It would be more flexible than this approach.

Also, please add unit tests.

**Comment by sagararora19992** [comment]
@VMRuiz All changes are completed.

**Review by VMRuiz — APPROVED** [review]
LGTM!

**Comment by VMRuiz** [comment]
Implements https://github.com/scrapinghub/shublang/issues/56

**Pull request merged**
